version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sistema_productos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sistema_productos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: